### ISSUE TITLE
Thanks for your new Greate Idea!

### ISSUE THREAD

**Issue by bemoregt** [neemiasbsilva/regression-in-CNNs-applied-to-plant-leaf-count#2]
HI, @neemiasbsilva 

Analyzing the CNN's GradCAM performing the classification, it visually highlights where in the input image it looks and classifies it. (E.g. geometric features)

if so ..

If you analyze the GradCAM of CNN performing the regression, it seems to be able to highlight what quantitative information in the input image and how to regress with a visual quantity. (Example: number, length, area, location, temperature, ...)

By the way, how can the GradCAM of the regression CNN network, which is different from the classification network, be calculated?

Thanks for your new Greate Idea!

Best,

@bemoregt.

**Comment by neemiasbsilva** [comment]
Thank you @bemoregt 

It's a good point,

I think you can be started to read this paper for better comprehension about the GradCAM in Regression approach for plant leaf count: https://openaccess.thecvf.com/content_CVPRW_2019/papers/CVPPP/Dobrescu_Understanding_Deep_Neural_Networks_for_Regression_in_Leaf_Counting_CVPRW_2019_paper.pdf


Anyway, thanks for the feedback 😄 !
