### ISSUE TITLE
must the images match label in csv file?

### ISSUE THREAD

**Issue by zhou-rui1** [neemiasbsilva/regression-in-CNNs-applied-to-plant-leaf-count#3]
Hi, I am following your work and I have a question:

Can I just add images without adding label in the csv to improve prediction , or is there a must to match them with the csv manually?

With regards, any guidance would be so grateful!

**Comment by zhou-rui1** [comment]
when my data has both the rgb and gray image, got this:
`X_datas = np.asarray(X_datas)
ValueError: could not broadcast input array from shape (299,299,3) into shape (299,299)`
how should I do, can it train with gray image?
With regards, hoping for your guidance!

**Comment by neemiasbsilva** [comment]
Hi Zhou,

Thanks for the interest :).

You can't add images without labels, you have to put in the CSV file.

About the error, I use three channels (RGB), you can not train if the image is binary.

I hope the best for you,

Thanks!

**Comment by zhou-rui1** [comment]
Thanks so much ! 

I can not get the test dataset now, could you share it  (google drive)?

With regards, by zhou

**Comment by zhou-rui1** [comment]
Thanks so much! 

One more question: how did you combine A1_A2_A3_A4 images in one folder, since some of the name seems to overlap？

With regards !

**Comment by neemiasbsilva** [comment]
I create a script in Python to merge the folders and the CSV files.

Best!

**Comment by DVAGA** [comment]
Hello, I'm trying to relocate your network, but I can't, because I can't find the .csv file is it possible to send me? If not, I would like to have some indication in order to be able to create it.

**Comment by neemiasbsilva** [comment]
About the csv file I upload in repository, please use `git pull` for update.

For you use this dataframe, you have to download the images, that are available in plant CVPP competition: https://www.plant-phenotyping.org/CVPPP2017-CFP

Best!
